"""Pydantic models for message types."""

from __future__ import annotations

from typing import Annotated, Any, Literal

from pydantic import Field

from opencode.models._base import OpenCodeModel
from opencode.models.common import FileDiff, ModelConfig
from opencode.models.error import MessageError
from opencode.models.part import Part


class UserMessageTime(OpenCodeModel):
    """Timestamp information for user messages."""

    created: float
    """Unix timestamp when the message was created."""


class UserMessageSummary(OpenCodeModel):
    """Summary information for a user message.

    Contains optional title and body text, along with any file diffs
    associated with the message.
    """

    title: str | None = None
    """Optional title for the summary."""

    body: str | None = None
    """Optional body text for the summary."""

    diffs: list[FileDiff]
    """List of file diffs associated with this message."""


class UserMessage(OpenCodeModel):
    """A message sent by the user.

    Contains the user's input along with metadata about the session,
    agent, and model configuration.
    """

    id: str
    """Unique identifier for this message."""

    session_id: str = Field(alias="sessionID")
    """ID of the session this message belongs to."""

    role: Literal["user"]
    """Role discriminator, always 'user' for user messages."""

    time: UserMessageTime
    """Timestamp information for this message."""

    summary: UserMessageSummary | None = None
    """Optional summary information for this message."""

    agent: str
    """The agent handling this message."""

    model: ModelConfig
    """The model configuration for this message."""

    system: str | None = None
    """Optional system prompt override."""

    tools: dict[str, Any] | None = None
    """Optional tools configuration."""


class AssistantMessageTime(OpenCodeModel):
    """Timestamp information for assistant messages."""

    created: float
    """Unix timestamp when the message was created."""

    completed: float | None = None
    """Unix timestamp when the message was completed, or None if still in progress."""


class AssistantMessagePath(OpenCodeModel):
    """Path context for an assistant message.

    Contains the current working directory and project root
    at the time the message was processed.
    """

    cwd: str
    """Current working directory."""

    root: str
    """Project root directory."""


class CacheTokens(OpenCodeModel):
    """Token usage for cache operations."""

    read: int
    """Number of tokens read from cache."""

    write: int
    """Number of tokens written to cache."""


class TokenUsage(OpenCodeModel):
    """Token usage statistics for a message.

    Tracks input, output, and reasoning tokens, as well as
    cache read/write statistics.
    """

    input: int
    """Number of input tokens consumed."""

    output: int
    """Number of output tokens generated."""

    reasoning: int
    """Number of reasoning tokens used."""

    cache: CacheTokens
    """Cache token usage statistics."""


class AssistantMessage(OpenCodeModel):
    """A message generated by the assistant.

    Contains the assistant's response along with metadata about
    token usage, costs, and any errors that occurred.
    """

    id: str
    """Unique identifier for this message."""

    session_id: str = Field(alias="sessionID")
    """ID of the session this message belongs to."""

    role: Literal["assistant"]
    """Role discriminator, always 'assistant' for assistant messages."""

    time: AssistantMessageTime
    """Timestamp information for this message."""

    error: MessageError | None = None
    """Error information if the message failed, or None if successful."""

    parent_id: str = Field(alias="parentID")
    """ID of the parent message (typically the user message this responds to)."""

    model_id: str = Field(alias="modelID")
    """ID of the model used to generate this message."""

    provider_id: str = Field(alias="providerID")
    """ID of the provider used to generate this message."""

    mode: str
    """The mode used for generation."""

    path: AssistantMessagePath
    """Path context at the time of message generation."""

    summary: bool | None = None
    """Whether this message is a summary."""

    cost: float
    """Cost of generating this message."""

    tokens: TokenUsage
    """Token usage statistics for this message."""

    finish: str | None = None
    """Finish reason for the message generation."""


Message = Annotated[
    UserMessage | AssistantMessage,
    Field(discriminator="role"),
]
"""Union type representing either a user or assistant message."""


class MessageWithParts(OpenCodeModel):
    """A message with its associated content parts.

    Combines message metadata with the actual content parts
    that make up the message body.
    """

    info: Message
    """The message metadata and information."""

    parts: list[Part]
    """The content parts that make up this message."""
